# Generated by Django 5.0.4 on 2025-12-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.FloatField()),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('twelfth_percentage', models.FloatField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('soft_skills', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
