# Generated by Django 5.0.4 on 2025-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_bio_userprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recruitment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='PENDING', max_length=20),
        ),
    ]
